CREATE TABLE JOURNAL (
    SEQ BIGINT AUTO_INCREMENT PRIMARY KEY,
    AGGREGATE_ID VARCHAR NULL,
    AGGREGATE_TYPE VARCHAR NULL,
    WHO VARCHAR NOT NULL,
    TS TIMESTAMP NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    EVENT_VERSION BIGINT NOT NULL,
    EVENT_SEQ BIGINT NOT NULL,
    EVENT_DATA CLOB NULL,
    UNIQUE_IDX VARCHAR GENERATED ALWAYS AS (AGGREGATE_TYPE || '-' || AGGREGATE_ID || '-' || EVENT_SEQ) UNIQUE
);

CREATE TABLE ORDER_OVERVIEW (
    ORDER_ID VARCHAR PRIMARY KEY,
    ITEM_COUNT INTEGER NOT NULL,
    ORDER_STATUS VARCHAR NOT NULL
);

CREATE TABLE VIEW_OFFSETS (
    VIEW_NAME VARCHAR PRIMARY KEY,
    VIEW_OFFSET BIGINT NOT NULL
);